from django.urls import path, include
from . import views

urlpatterns = [
    path ('', views.index),
    path ('drinkjs', views.drinks_list_json),
    path ('addStock', views.add_stock), 
    path ('addTask', views.add_task),
    path ('addDrink', views.add_drink),
    path ('addDesert', views.add_desert),
    path ('addAddit', views.add_addit),
    path ('addUser', views.add_user),
    path ('stock/del/', views.del_stock), 
    path ('task/del/', views.del_task), 
    path ('user/del/', views.del_user), 
    path ('additives/del/', views.del_additives),
    path ('desert/del/', views.del_deserts),
    path ('menu/del/', views.del_drink),
    path ('user/edit/', views.editBarista),
    path ('menu/edit/', views.editMenu),
    path ('desert/edit/', views.editDesert),
    path ('additives/edit/', views.editAdditives),
    path ('task', views.task),
    path ('avt', views.avt),
    path ('add', views.add),
    path ('set', views.set),
    path ('menu',views.menu),
    path ('menu2',views.menu2,),
    path ('des',views.des),
    path ('barista', views.barista),
    path ('barista/add/', views.add_barista),
    path ('cheklist', views.cheklist),
    path ('doc', views.doc),
    path ('inv',views.inv),
    path ('stock', views.stock),
    path ('one', views.one),
    path ('two', views.two),
    path ('three', views.three),
    path ('four',views.four),
    path ('five', views.five),
    path ('six', views.six),
    path ('sev', views.sev),
    path ('eight',views.eight),
    path ('nine', views.nine),
    path ('ten', views.ten),
    path ('el', views.el),
    path ('inv2', views.inv2),
    path ('mor',views.mor),
    path ('evn', views.evn),
    path('accounts/', include('django.contrib.auth.urls'))
]


