# Generated by Django 4.2.13 on 2024-06-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Additives",
            fields=[
                ("idadditives", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("category", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "additives",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Deserts",
            fields=[
                ("iddeserts", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "deserts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                ("idmenu", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("position_name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "menu",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("idstock", models.AutoField(primary_key=True, serialize=False)),
                ("stockc_name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "stock",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("idtask", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "task",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("iduser", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sername", models.CharField(max_length=100)),
                ("login", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
    ]
